name: Pull Request Main

on:
    push: 
        branches:
            - dev 

permissions:
  contents: write
  pull-requests: write

jobs: 
    sync-dev-preprod:
        name: Create or update pull request to main 
        runs-on: ubuntu-latest

        steps: 
            - name: Set up Git
              run: |
                  git config --global user.email "matiasjats@gmail.com"
                  git config --global user.name "Matias jara"

            - name: Checkout repo
              uses: actions/checkout@v3
              
            - name: Create Pull request
              uses: peter-evans/create-pull-request@v5
              with: 
                token: ${{ secrets.GITHUB_TOKEN }}
                base: main
                branch: dev
                title: "Merge dev into main"
                body: |
                  This PR was automatically create by Github Actions by Matias
                draft: false
                delete-branch: false
           

   
