name: Create PR from dev to main

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: dev  # Asegurarse de trabajar con la rama dev

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main   # Rama destino
          head: dev    # Rama fuente
          title: "Merge dev into main"
          body: "This PR was automatically created by GitHub Actions"
          draft: false
          delete-branch: false
          commit-message: "Update from dev branch"