name: Sync dev to main, build, test and deploy with Docker

on:
    push: 
        branches:
            - dev 

permissions:
  contents: write

jobs: 
    sync-dev-preprod:
        name: Sync dev and main
        runs-on: ubtuntu-latest

        steps: 
            - name: Checkout main branch
              uses: actions/checkout@v3
              with:
                ref: main

            - name: Set up Git
              run: |
                 git config --global user.email "matiasjats@gmail.com"
                 git config --global user.name "Matias jara"

            - name: Merge to main
              run: |
                 git fetch origin dev
                 git merge origin/dev --no-ff -m "Merge dev into pre-prod via CI"

            - name: Push main Branch
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                 git push origin main
            
            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '21'

            - name: Build with Maven
              run: mvn clean install
                        
            - name: Run tests
              run: mvn test

            - name: Build Docker image
              run: docker build -t api-tasks-main .
   