name: Deploy to Pre-Staging

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
      
      - name: Build with Maven
        run: mvn clean install
         
      - name: Run test
        run: mvn test

      # Aquí irán los pasos para build, test y deploy
